### ISSUE TITLE
Project active?

### ISSUE THREAD

**Issue by jnarowski** [cj/vuex-form#3]
This seems like a pretty interesting project but doesn't seem active. Do you plan to continue developing it?

**Comment by yapus** [comment]
just tried and cannot get it working with the latest vue.js 2.x

**Comment by cj** [comment]
@jnarowski it's not currently active, but I plan to reboot the project in the coming months!

**Comment by jnarowski** [comment]
@cj let's chat when you do. I think the idea is great and def needed in the vue/vuex world. I'd be willing to help!
